### ISSUE TITLE
ImportError: cannot import name 'dataclass' from 'attr'

### ISSUE THREAD

**Issue by mrichman** [psf/black#985]
Operating system: macOS 10.14.6
Python version: 3.7.4
*Black* version: 19.3b0
Does also happen on master: No idea - just did `pip3 install --user black`

I installed black, ran `black` and got this error:

```
Traceback (most recent call last):
  File "/User/Mark/Library/Python/3.7/bin/black", line 6, in <module>
    from black import patched_main
  File "/User/Mark/Library/Python/3.7/lib/python/site-packages/black.py", line 40, in <module>
    from attr import dataclass, evolve, Factory
ImportError: cannot import name 'dataclass' from 'attr' (/User/Mark/Library/Python/3.7/lib/python/site-packages/attr.py)
```

**Comment by hugovk** [comment]
What version of `attrs` do you have installed?

I have:

```console
$ pip freeze | grep attrs
attrs==19.1.0
```

`dataclass` was added to attrs in 19.1.0, I guess you have something older than 19.1.0.

* https://github.com/python-attrs/attrs/commit/88aa1c897dfe2ee4aa987e4a56f2ba1344a17238

Try `pip install -U attrs` or `pip install "attrs>=19.1.0"` and run Black again.

**Comment by hugovk** [comment]
> `dataclass` was added to attrs in 19.1.0, I guess you have something older than 19.1.0.

Correction: it was added in 17.3.0.

I can reproduce when downgrading to 17.2.0 (`pip install "attrs<17.3"`) and it goes away when upgrading to 19.1.0.

Black requires 18.1.0+ so it should've been updated when you installed Black:

https://github.com/psf/black/blob/40e8b3a231bade22d838858435a33d60a8325306/setup.py#L46

**Comment by mrichman** [comment]
I have 19.1.0:

```
pip freeze | grep attrs
attrs==19.1.0
cattrs==0.9.0
```

**Comment by mrichman** [comment]
Looks like I had a conflicting (unrelated) package called `attr` in my `site-packages`

```
pip uninstall attr
Uninstalling attr-0.3.1:
  Would remove:
    /User/Mark/Library/Python/3.7/lib/python/site-packages/attr-0.3.1.dist-info/*
    /User/Mark/Library/Python/3.7/lib/python/site-packages/attr.py
    /User/Mark/Library/Python/3.7/lib/python/site-packages/dry_attr.py
```
Now `black` works:

```
black
No paths given. Nothing to do 😴
```

**Comment by mrichman** [comment]
This is the offending package, in case anyone else hits this issue: https://pypi.org/project/attr/

**Comment by hugovk** [comment]
Oh, how annoying! But good find!
