### ISSUE TITLE
ImportError: cannot import name '_unicodefun' from 'click'

### ISSUE THREAD

**Issue by enaskopelja** [psf/black#2976]
**Describe the bug**
A recent version of `click` has been released which removes `_unicodefun`, breaking `black` (see also https://github.com/dask/distributed/issues/6013).

**To Reproduce**

```bash
docker run --rm -it python:3.9-alpine sh
```

In the container:
```
pip install "click==8.1.0" "black==22.1.0"
black .
```
The resulting error is:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/usr/local/lib/python3.9/site-packages/black/__init__.py", line 1423, in patched_main
    patch_click()
  File "/usr/local/lib/python3.9/site-packages/black/__init__.py", line 1409, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/usr/local/lib/python3.9/site-packages/click/__init__.py)
```

**Comment by zerocewl** [comment]
maybe pin `click` to the version before? `click==8.0.2`

see also https://github.com/dask/distributed/issues/6013

**Comment by jack1142** [comment]
This has been fixed by Black 22.3.0. Versions before that won't work with click 8.1.0.

**Comment by felix-hilden** [comment]
Correct, see issue #2964 for more info.
