### PR TITLE
Fix _unicodefun patch code for Click 8.1.0

### LINKED ISSUE #2964: Github Action Fails with ImportError from 'click'
**Describe the bug**

The Github Action step:

```
- name: Run black
  uses: psf/black@stable
  with:
     options: "--check --diff"
      version: "22.1.0"
```

fails with the following trackeback:

```
Traceback (most recent call last):
  File "/home/runner/work/_actions/psf/black/stable/.black-env/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1[40](https://github.com/stumpylog/paperless-ngx/runs/5724998040?check_suite_focus=true#step:7:40)9, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/work/_actions/psf/black/stable/.black-env/lib/python3.8/site-packages/click/__init__.py)
```

**To Reproduce**

Run the `black` action on a Github runner, configured as above.

**Expected behavior**

The action should only fail if files are not formatted.

**Environment**

OS: `runs-on: ubuntu-20.04`
Version: `22.1.0`
Action: `@stable`
Python version: `3.8` I believe

**Additional context**

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #2964

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Merging now because I'm pretty sure this isn't going to break PyPy on MacOS only.

**Comment by tjeck97** [comment]
breaks `black==19.10b0`

`ImportError: cannot import name '_unicodefun' from 'click'`

**Comment by JelleZijlstra** [comment]
@tjeck97 black 19.10b0 is old. Please upgrade.

**Comment by tjeck97** [comment]
> @tjeck97 black 19.10b0 is old. Please upgrade.

well now i'm forced to :sweat_smile: though pinning `click<8.1.0` also fixes.

**Comment by mirayyuce** [comment]
With Version: 22.1.0 I still get the same error

**Comment by JelleZijlstra** [comment]
This PR was released in version 22.3.0.

File: .github/workflows/diff_shades.yml [hunk 1]
```diff
@@ -24,7 +24,7 @@ jobs:
 
       - name: Install diff-shades and support dependencies
         run: |
-          python -m pip install click packaging urllib3
+          python -m pip install 'click<8.1.0' packaging urllib3
```
Comment (cooperlees) [inline .github/workflows/diff_shades.yml:27]: Why do we pin < 8.1.0 if this fixes the bug? What am I missing - Is this for diff-shades?

Comment (JelleZijlstra) [reply .github/workflows/diff_shades.yml:27]: There's another bug, https://github.com/pallets/click/issues/2227

Comment (ichard26) [reply .github/workflows/diff_shades.yml:27]: Click 8.1.0 breaks mypyc (and probably mypy in general) as it both deleted internal APIs we import and also had a bad typing change (Jelle would have the link).

Comment (cooperlees) [reply .github/workflows/diff_shades.yml:27]: Ahh ok - I just read this below and was super confused as to why we pinned: 
```markdown
- Fix Black to work with Click 8.1.0 (#2966)
```
Cheers

**Comment by vhosakot** [comment]
> This PR was released in version 22.3.0.

can confirm this issue is fixed in black `22.3.0`.

**Comment by krmannix** [comment]
I had `21.10b0` pinned, and it began to break with the release of `22.3.0` with an error that looks related to this change.
```
ImportError: cannot import name '_unicodefun' from 'click'
```

Genuine question - why would an older version be impacted by the release of a newer version?

**Comment by jack1142** [comment]
The old release of black is affected by a new release of `click` (black < 22.3.0 does not work with click 8.1.0 and fixing this is part of the reason why black 22.3.0 was released in the first place), not a new release of black.

**Comment by JelleZijlstra** [comment]
@krmannix you almost certainly did not have 21.10b0 pinned, and (as @jack1142 said), your code started breaking when click 8.1.0 was released, not when Black 22.3.0 was released a few hours later.

**Comment by aaronbrezel** [comment]
I am running black 22.3.0 and click 8.1.0  and am still seeing this issue

**Comment by jack1142** [comment]
@aaronbrezel what is the issue you're seeing *exactly*? Because it cannot be the exact same as reported in #2964 if you actually updated because `ImportError` exceptions are now caught.

**Comment by aaronbrezel** [comment]
> @aaronbrezel what is the issue you're seeing _exactly_? Because it cannot be the exact same as reported in #2964 if you actually updated because `ImportError` exceptions are now caught.

I appreciate the quick response!

I run black using Github Actions. 

A truncated view of my installation process:
```
Collecting black>=22.3.0
  Downloading black-22.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
...
Successfully installed ... black-22.3.0 ... click-8.1.0 ...
```
The action then runs:
```
pre-commit run --all-files
```
to check for proper linting and formatting.

This results in the following error:
```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo4s5v_ps5/py_env-python3.9/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repo4s5v_ps5/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1282, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repo4s5v_ps5/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1268, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repo4s5v_ps5/py_env-python3.9/lib/python3.9/site-packages/click/__init__.py)
```

**Comment by jack1142** [comment]
@aaronbrezel pre-commit uses an isolated virtual environment so you need to make sure that you update the version of Black in `.pre-commit-config.yaml`.

**Comment by aaronbrezel** [comment]
> @aaronbrezel pre-commit uses an isolated virtual environment so you need to make sure that you update the version of Black in `.pre-commit-config.yaml`.

Ah that's it! Thank you very much for the quick help
